FROM python:3.12
WORKDIR /app

# 复制源代码
COPY . .

# 安装依赖
RUN pip install --no-cache-dir -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple --extra-index-url https://pypi.org/simple

# 暴露端口
EXPOSE 9399

# 启动命令
CMD ["python", "app.py", "--env=dockermy"]