FROM python:3.12
WORKDIR /app

# 复制源代码
COPY . .

# 安装依赖
RUN pip install --no-cache-dir -r requirements-pg.txt -i https://pypi.tuna.tsinghua.edu.cn/simple

# 暴露端口
EXPOSE 9399

# 启动命令
CMD ["python", "app.py", "--env=dockerpg"]